# Generated by Django 5.0 on 2024-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_announcement_broadcast_circular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='club_logos/')),
                ('details', models.TextField()),
                ('official_link', models.URLField()),
            ],
        ),
    ]
