# Generated by Django 5.0 on 2024-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='official_link',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
        migrations.AddField(
            model_name='club',
            name='link',
            field=models.URLField(default='uvce.ac.in'),
        ),
    ]
